#!/bin/bash

mkdir build
cd build

BUILD_CONFIG=Release

if [[ ${PY3K} -eq 1 ]]; then
    ADDITIONAL_CMAKE_FLAGS="$ADDITIONAL_CMAKE_FLAGS -DPYTHON_VERSION_MAJOR=3 "
else
    ADDITIONAL_CMAKE_FLAGS="$ADDITIONAL_CMAKE_FLAGS -DPYTHON_VERSION_MAJOR=2 "
fi

# Kept systemn flags 
#   GDCM_USE_SYSTEM_PAPYRUS3
#   GDCM_USE_SYSTEM_SOCKETXX
#   GDCM_USE_SYSTEM_CHARLS
 
cmake .. -G "Ninja" \
    -Wno-dev \
    -DCMAKE_BUILD_TYPE=$BUILD_CONFIG \
    -DCMAKE_PREFIX_PATH=${PREFIX} \
    -DCMAKE_INSTALL_PREFIX:PATH="$PREFIX" \
    -DCMAKE_INSTALL_RPATH:PATH="$PREFIX/lib" \
    -DGDCM_USE_SYSTEM_EXPAT:BOOL=ON \
    -DGDCM_USE_SYSTEM_ZLIB:BOOL=ON \
    -DGDCM_USE_SYSTEM_UUID:BOOL=ON \
    -DGDCM_USE_SYSTEM_OPENJPEG:BOOL=ON \
    -DGDCM_USE_SYSTEM_OPENSSL:BOOL=ON \
    -DGDCM_USE_SYSTEM_JSON:BOOL=ON \
    -DGDCM_USE_SYSTEM_LJPEG:BOOL=ON \
    -DGDCM_BUILD_SHARED_LIBS:BOOL=ON \
    -DGDCM_BUILD_APPLICATIONS:BOOL=ON \
    -DGDCM_BUILD_TESTING:BOOL=OFF \
    -DGDCM_BUILD_EXAMPLES:BOOL=OFF \
    -DGDCM_BUILD_APPLICATIONS=OFF \
    -DGDCM_USE_VTK:BOOL=OFF \
    -DGDCM_WRAP_PYTHON:BOOL=ON \
    -DGDCM_DOCUMENTATION:BOOL=OFF \
    -DGDCM_BUILD_DOCBOOK_MANPAGES:BOOL=OFF \
    -DSWIG_EXECUTABLE:FILEPATH=${BUILD_PREFIX}/bin/swig \
    -DGDCM_INSTALL_PYTHONMODULE_DIR:PATH=$SP_DIR \
    -DGDCM_INSTALL_NO_DOCUMENTATION:BOOL=ON \
    -DGDCM_INSTALL_NO_DEVELOPMENT:BOOL=ON \
    $ADDITIONAL_CMAKE_FLAGS

ninja install
