{% set version = "2.8.6" %}

package:
  name: gdcm
  version: {{ version }}

source:
  url: https://github.com/malaterre/GDCM/archive/v{{ version }}.tar.gz
  fn: GDCM-{{ version }}.tar.gz
  sha256: f4e611c74ea2b16c9aa28d7fdf3a8678ce926909606705b7cd08c9a5b05d34fc

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - toolchain
    - cmake
    - ninja
    - python
    - swig
  run:
    - python

test:
  imports:
    - gdcm

about:
  home: https://sourceforge.net/p/gdcm/gdcm/
  license: BSD-2-Clause
  summary: Grassroots DICOM, cross-platform DICOM implementation.

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
