{% set version = "3.0.1" %}
{% set native = 'm2w64-' if win else '' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: gdcm
  version: {{ version }}

source:
  url: https://github.com/malaterre/GDCM/archive/v{{ version }}.tar.gz
  fn: GDCM-{{ version }}.tar.gz
  sha256: f1ee8ebda7a465281abada329b4dbca6e036a42ead6ad58070ff4f94da7819d9
  patches:
    # patch for statically linked python
    # https://stackoverflow.com/questions/50085173/swig-with-anaconda-environment-on-mac-os-throws-fatal-python-error-pythreadstat
    - swig.patch  # [osx]

build:
  number: 0
  ignore_run_exports:
    - libuuid  # [unix]

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}    # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - pkg-config             # [unix]
    - swig
    - m2w64-pkg-config        # [win]
    - m2w64-toolchain        # [win]
  host:
    - python
    # TODO: We need to add more things
    - libuuid  # [unix]
    - zlib
    - openjpeg
    - expat
    - json-c
    - libpython  # [win]
    - libjpeg-turbo
  run:
    - python
    - json-c

test:
  commands:
    - python -v -c "import gdcm"

about:
  home: https://sourceforge.net/p/gdcm/gdcm/
  license: BSD-2-Clause
  summary: Grassroots DICOM, cross-platform DICOM implementation.

extra:
  recipe-maintainers:
    - ivoflipse
    - mariusvniekerk
