{% set version = "2.8.5" %}

package:
  name: gdcm
  version: {{ version }}

source:
  url: https://github.com/malaterre/GDCM/archive/v{{ version }}.tar.gz
  fn: GDCM-{{ version }}.tar.gz
  sha256: ac6e0f065ed1fa5568173c1ca9f34fce50e7ea15c95a32f6a6ef064141fd2269

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - toolchain
    - cmake
    - ninja
    - python
    - swig
  run:
    - python

test:
  imports:
    - gdcm

about:
  home: https://sourceforge.net/p/gdcm/gdcm/
  license: BSD-2-Clause
  summary: Grassroots DICOM, cross-platform DICOM implementation.

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
