{% set version = "2.8.4" %}

package:
  name: gdcm
  version: {{ version }}

source:
  url: https://github.com/malaterre/GDCM/archive/v{{ version }}.tar.gz
  fn: GDCM-{{ version }}.tar.gz
  sha256: c0859b306865c689cb570f5e2450417642cd95988960682cff0c675e0ff0732d

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - swig
  run:
    - python

test:
  imports:
    - gdcm

about:
  home: https://sourceforge.net/p/gdcm/gdcm/
  license: BSD-2-Clause
  summary: Grassroots DICOM, cross-platform DICOM implementation.

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
