appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rXNLASupVQ+buc1PKB57I/hiPINY9l1B7Oh88wFB1D5Z1Vjyn4Lx0hLr+f91tIOL5IAGOvRLBuHakghbL3JvHTdHHqiGTQx1pThxw35EK5eny513kX64qZA8DHZ8e2qY2r5Rjrhm1iw2ZE+d6ghJHKZMk6h/biaVWGOo0xYEubuvHuDrq9yLstCvrHId4JsFtLx8VPcy5g693D2lkc13X9JiI6JfE9V5/YGhfEaIwgCaXO9NOOsH3hja/dt1JkyQSW0eVQcM0XZcmsWHBJSnK2tWDy8NMlCSEgEw11nIJv00jkmljOTQg8iFCZ6ROE/INyvxYjh2N0JVSMQYdqLGtZoyJPdJ0uv8GJXeNRxH8myHsi9V0RpAptMNREXAPoXAnp5Wr7zaJ/N1pJRXzE/iNBLXaVSHm8v9IRMzJ/YCeExsKVXzzejW0RNIhsuHkxSj20Nt3JMAAQY7CuQ5XJcajzeC9cO1zGQCt8kq3zPLT7KU1ZSKemoE3sQXYpKrlAzXHhIAGbFSmSrZfvoNyS+CWYkSKOE6YNO2HoYSY9UYMHRifeMi7WDGKRKjzVdpOjzL/GynDwW/0werlVKYIPJGHcL217gGaiy60Rh4UxrRKqUjPp+EZOfqTA9hLjCCdZsDB1T0N2MJlXzQq3BclC7onaxezy9J6NoP2vtnM+sAeGc=}
